apiVersion: automation.cloudbees.io/v1alpha1
kind: CustomJob
name: manual approval
description: Request manual approval from users and teams

inputs:
  approvers:
    description: Comma separated list of approvers. Can be users or teams. If not specified, then all users who have execute permission for approval on the workflow can approve.
    required: false
  instruction:
    description: Text to display in the approval prompt
    required: false
  disallowLaunchByUser:
    description: For separation of responsibilities, if true, then the user who launched the workflow is not allowed to approve.
    required: false

handlers:
  init:
    uses: docker://esolang/jq:latest
    command: /bin/sh
    args: |
      -c """
      # Manual approval template
      TEMPLATE='{\"approvers\": ($a | split(\",\")), \"disallowLaunchByUser\": $d}'
      [ -n "$INSTRUCTION" ] && TEMPLATE='{\"approvers\": ($a | split(\",\")), \"instruction\": $i, \"disallowLaunchByUser\": $d}'

      # Build valid JSON
      JSON_PAYLOAD=$(/usr/bin/jq -n --arg a \"$APPROVERS\" --arg i \"$INSTRUCTION\" --argjson d \"${DISALLOW_LAUNCHED_BY_USER:-false}\" \"$TEMPLATE\")

      # To avoid issue 'argument list too long' use file
      echo \"$JSON_PAYLOAD\" > /tmp/content.json

      # Make Platform API call
      response=$(curl -s --fail-with-body -X 'POST' \"$URL/v1/workflows/approval\" \
        -H \"Authorization: Bearer ${API_TOKEN}\" -H 'Content-Type: application/json' -H 'Accept: application/json' \
        --data-binary \"@/tmp/content.json\") || command_failed=1

      # Check curl exit code
      if [ ${command_failed:-0} -eq 1 ];
      then
        echo \"Platform API call failed with error: '$response'\"
        
        # Save failure
        echo '{    
          \"status\": \"FAILED\",
          \"message\": \"Failed to initialize workflow manual approval with error: '$response'\"
        }' > $CLOUDBEES_STATUS
      
        exit 1
      fi

      # Save success
      if [ -z "$APPROVERS" ]; 
      then
        echo 'Waiting for approval'
      else
        echo 'Waiting for approval from one of the following: '$APPROVERS
      fi

      if [ -n \"$INSTRUCTION\" ]; 
      then
        echo 'Instructions:'
        echo $INSTRUCTION
      fi
      echo 'Thanks!'
      
      echo '{    
        \"status\": \"PENDING_APPROVAL\",
        \"message\": \"Waiting for approval from approvers\" 
      }' > $CLOUDBEES_STATUS
      """
    env:
      APPROVERS: ${{inputs.approvers}}
      INSTRUCTION: ${{inputs.instruction}}
      DISALLOW_LAUNCHED_BY_USER: ${{inputs.disallowLaunchByUser}}
      API_TOKEN: ${{ cloudbees.api.token }}
      URL: ${{ cloudbees.api.url }}

  callback:
    uses: docker://esolang/jq:latest
    command: /bin/sh
    args: |
      -c """
      
      #TODO: remove after debugging
      echo \"DEBUG: Payload: '$PAYLOAD'\"
      
      # Extract approved and comments fields from the payload in JSON format
      APPROVAL_STATUS=$(echo \"$PAYLOAD\" | /usr/bin/jq -r '.status')
      COMMENTS=$(echo \"$PAYLOAD\" | /usr/bin/jq -r '.comments')
      
      # Make Platform API call to change workflow manual approval status
      response=$(curl -s --fail-with-body  -X POST \"$URL/v1/workflows/approval/status\" -H \"Authorization: Bearer $API_TOKEN\" -H 'Content-Type: application/json' -d \"$PAYLOAD\") || command_failed=1
      
      # Check curl exit code
      if [ ${command_failed:-0} -eq 1 ];
      then
        echo \"Platform API call failed with error: '$response'\"

        # Save failure
        echo '{    
          \"status\": \"FAILED\",
          \"message\": \"Failed to change workflow manual approval status with error: '$response'\"
        }' > $CLOUDBEES_STATUS
      
        exit 1
      fi

      # Save success
      if [ "$APPROVAL_STATUS" == "UPDATE_MANUAL_APPROVAL_STATUS_APPROVED" ]; 
      then
        JOB_STATUS="APPROVED"
        echo 'Approval comments:'
      elif [ "$APPROVAL_STATUS" == "UPDATE_MANUAL_APPROVAL_STATUS_REJECTED" ];
      then
        JOB_STATUS="REJECTED"
        echo 'Rejection comments:'
      else
        echo \"Error: Unexpected approval status '$APPROVAL_STATUS'\"
        echo '{    
          \"status\": \"FAILED\",
          \"message\": \"Unexpected approval status encountered: '$APPROVAL_STATUS'\"
        }' > $CLOUDBEES_STATUS
      
        exit 1
      fi
      echo \"$COMMENTS\"
      
      echo '{    
        \"status\": '\\\"$JOB_STATUS\\\"',
        \"message\": \"Successfully changed workflow manual approval status\"
      }' > $CLOUDBEES_STATUS
      """
    env:
      API_TOKEN: ${{ cloudbees.api.token }}
      URL: ${{ cloudbees.api.url }}
      PAYLOAD: ${{ handler.payload }}

  cancel:
    uses: docker://alpine/curl:latest
    command: /bin/sh
    #to abort pending approval request in case of timeout or workflow abort event.
    args: |
      -c "
      # Make Platform API call to change workflow manual approval status
      response=$(curl -s --fail-with-body  -X POST \"$URL/v1/workflows/approval/status\" -H \"Authorization: Bearer $API_TOKEN\" -H 'Content-Type: application/json' -d '{\"status\": \"$CANCELLATION_REASON\"}') || command_failed=1
      
      # Check curl exit code
      if [ ${command_failed:-0} -eq 1 ];
      then
        echo \"Platform API call failed with error: '$response'\"
      "
    env:
      API_TOKEN: ${{ cloudbees.api.token }}
      URL: ${{ cloudbees.api.url }}
      CANCELLATION_REASON: ${{ handler.reason }}
