apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: manual-approval

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  main:
    steps:
    - name: Get source code
      uses: cloudbees-io/checkout@v1

    - id: build
      name: Build, scan and push to ECR
      uses: calculi-corp/cb-internal-shared-actions/build@v8
      with:
        go-binary-build: "true"
        go-binary-name: manual-approval
        kaniko-build: "true"
        trivy-scan-container: "true"
        registry-url: 020229604682.dkr.ecr.us-east-1.amazonaws.com
        registry-image-name: custom-jobs/manual-approval
        registry-type: ECR
        oidc-iam-role: ${{ vars.oidc_staging_iam_role }}

    - name: Check image
      uses: docker://alpine:3.18
      run: |
        apk add -U --no-cache curl ca-certificates
        curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 >/usr/local/bin/regctl
        chmod 755 /usr/local/bin/regctl

        EXPECTED=${{ steps.build.outputs.digest }}
        ACTUAL=`regctl image digest 020229604682.dkr.ecr.us-east-1.amazonaws.com/custom-jobs/manual-approval:${{ cloudbees.version }}`
        if [ "$EXPECTED" != "$ACTUAL" ]; then
          echo "expected $EXPECTED, but got $ACTUAL"
          exit 1
        fi

        regctl image inspect 020229604682.dkr.ecr.us-east-1.amazonaws.com/custom-jobs/manual-approval:${{ cloudbees.version }}
