apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: manual-approval

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  build:
    steps:
    - name: Get source code
      uses: cloudbees-io/checkout@v1

    - name: Unit tests
      uses: docker://golang:1.23
      run: |
        go test --cover ./...

    - name: Set up Docker Hub registry
      uses: cloudbees-io/configure-oci-credentials@v1
      with:
        registry: index.docker.io # or docker.io
        username: ${{ vars.TEMP_MANUAL_APPROVAL_DOCKER_USER }}
        password: ${{ secrets.TEMP_MANUAL_APPROVAL_DOCKER_PASSWORD }}

    - name: Build image
      id: build-image
      uses: cloudbees-io/kaniko@v1
      with:
        destination: index.docker.io/${{ vars.TEMP_MANUAL_APPROVAL_DOCKER_USER }}/manual-approval:${{ cloudbees.scm.sha }},index.docker.io/${{ vars.TEMP_MANUAL_APPROVAL_DOCKER_USER }}/manual-approval:latest
        labels: maintainer=cbp-cd-ro-team,email=engineering@cloudbees.io
        registry-mirrors: 020229604682.dkr.ecr.us-east-1.amazonaws.com/docker-hub

    - name: Run TruffleHog Container Action
      uses: cloudbees-io/trufflehog-secret-scan-container@v1
      with:
        image-location: index.docker.io/${{ vars.TEMP_MANUAL_APPROVAL_DOCKER_USER }}/manual-approval
        image-tag: ${{ cloudbees.scm.sha }}
  
  test:
    needs: [build]
    steps:
    - name: Get source code
      uses: cloudbees-io/checkout@v1

    - name: Set up Docker Hub registry
      uses: cloudbees-io/configure-oci-credentials@v1
      with:
        registry: index.docker.io # or docker.io
        username: ${{ vars.TEMP_MANUAL_APPROVAL_DOCKER_USER }}
        password: ${{ secrets.TEMP_MANUAL_APPROVAL_DOCKER_PASSWORD }}

    - name: Build test image
      id: build-test-image
      uses: cloudbees-io/kaniko@v1
      with:
        destination: index.docker.io/${{ vars.TEMP_MANUAL_APPROVAL_DOCKER_USER }}/manual-approval-test:${{ cloudbees.scm.sha }}
        labels: maintainer=cbp-cd-ro-team,email=engineering@cloudbees.io
        registry-mirrors: 020229604682.dkr.ecr.us-east-1.amazonaws.com/docker-hub

    - name: Check test image
      uses: docker://alpine:3.18
      run: |
        apk add -U --no-cache curl ca-certificates
        curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 >/usr/local/bin/regctl
        chmod 755 /usr/local/bin/regctl

        EXPECTED=${{ steps.build.outputs.digest }}
        ACTUAL=`regctl image digest index.docker.io/${{ vars.TEMP_MANUAL_APPROVAL_DOCKER_USER }}/manual-approval-test:${{ cloudbees.scm.sha }}`
        if [ "$EXPECTED" != "$ACTUAL" ]; then
          echo "expected $EXPECTED, but got $ACTUAL"
          exit 1
        fi
             
        regctl image inspect index.docker.io/${{ vars.TEMP_MANUAL_APPROVAL_DOCKER_USER }}/manual-approval-test:${{ cloudbees.scm.sha }}
